'use client';
import {useState,useEffect,useRef} from 'react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {ScorePicker,StoolPicker,UrgencyPicker,stoolLabels} from './symptom-controls';
import {japanToday,japanTime,type DiaryData,type Meal,type SymptomEvent,type MealTransfer,type DailySymptoms} from '@/lib/diary';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type DailyFields={pain:string;bloating:string;stool:string;stress:string;sleep:string;bowelCount:string;urgency:string;note:string};
type EventFields={time:string;pain:string;bloating:string;stool:string;urgency:string;note:string};
const blankDaily:DailyFields={pain:'',bloating:'',stool:'',stress:'',sleep:'',bowelCount:'',urgency:'',note:''};
const blankEvent=():EventFields=>({time:japanTime(),pain:'',bloating:'',stool:'',urgency:'',note:''});
const emptyData:DiaryData={meals:[],symptoms:null,events:[],deletedMeals:[],deletedEvents:[]};
const num=(value:string)=>value.trim()===''?null:Number(value);
function dailyFields(s:DailySymptoms|null):DailyFields{return s?{pain:s.pain?.toString()??'',bloating:s.bloating?.toString()??'',stool:s.stool?.toString()??'',stress:s.stress?.toString()??'',sleep:s.sleep?.toString()??'',bowelCount:s.bowel_count?.toString()??'',urgency:s.urgency?.toString()??'',note:s.note}:blankDaily}
export default function Diary({transfer,onChanged}:{transfer:MealTransfer|null;onChanged:()=>void}){
 const [date,setDate]=useState(japanToday);const [time,setTime]=useState(japanTime);const [kind,setKind]=useState('昼食');const [food,setFood]=useState('');const [amount,setAmount]=useState('');const [editing,setEditing]=useState<string|null>(null);
 const [fields,setFields]=useState<DailyFields>(blankDaily);const dailyDrafts=useRef(new Map<string,DailyFields>());
 const [event,setEvent]=useState<EventFields>(blankEvent);const [eventEditing,setEventEditing]=useState<string|null>(null);
 const [data,setData]=useState<DiaryData>(emptyData);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [auth,setAuth]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [incoming,setIncoming]=useState<MealTransfer|null>(null);
 const transferToken=useRef('');const mealId=useRef('');const eventId=useRef('');const formRef=useRef<HTMLFormElement>(null);
 useEffect(()=>{if(!transfer||transfer.token===transferToken.current)return;transferToken.current=transfer.token;if(food.trim()||editing){setIncoming(transfer)}else{setFood(transfer.food);setAmount(transfer.amount);mealId.current='';setSuccess('材料を引き継ぎました。実際に食べた時刻・量を確認して保存してください。')}},[transfer,food,editing]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');setData(emptyData);fetch('/api/diary?date='+date,{signal:abort.signal,cache:'no-store'}).then(async r=>{const v=await r.json() as DiaryData & {error?:string};if(!r.ok){setAuth(r.status===401);throw new Error(v.error)}if(abort.signal.aborted)return;setAuth(false);setData(v);setFields(dailyDrafts.current.get(date)??dailyFields(v.symptoms))}).catch(e=>{if(!abort.signal.aborted)setError(e.message??'記録を読み込めません。')}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[date]);
 function setDaily(patch:Partial<DailyFields>){const next={...fields,...patch};setFields(next);dailyDrafts.current.set(date,next)}
 async function refresh(){const r=await fetch('/api/diary?date='+date,{cache:'no-store'});const v=await r.json() as DiaryData & {error?:string};if(!r.ok)throw new Error(v.error);setData(v)}
 async function mutate(method:string,body:unknown,message:string){setSaving(true);setError('');setSuccess('');try{const r=await fetch('/api/diary',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json() as DiaryData & {error?:string};if(!r.ok){if(r.status===401)setAuth(true);throw new Error(v.error)}setSuccess(message);onChanged();try{await refresh()}catch{setError('保存は完了しましたが、一覧を更新できませんでした。再読み込みしてください。')}return true}catch(e){setError(e instanceof Error?e.message:'保存できませんでした。入力内容は残っています。');return false}finally{setSaving(false)}}
 async function saveMeal(){if(!mealId.current)mealId.current=crypto.randomUUID();if(await mutate(editing?'PATCH':'POST',{type:'meal',id:editing??mealId.current,date,time,kind,food,amount},editing?'食事を更新しました。':'食事を保存しました。')){setFood('');setAmount('');setEditing(null);mealId.current=''}}
 async function saveEvent(){if(!eventId.current)eventId.current=crypto.randomUUID();if(await mutate(eventEditing?'PATCH':'POST',{type:'event',id:eventEditing??eventId.current,date,time:event.time,pain:num(event.pain),bloating:num(event.bloating),stool:num(event.stool),urgency:num(event.urgency),note:event.note},'時刻別の体調を保存しました。')){setEvent(blankEvent());setEventEditing(null);eventId.current=''}}
 async function saveDaily(){if(await mutate('POST',{type:'symptoms',id:crypto.randomUUID(),date,pain:num(fields.pain),bloating:num(fields.bloating),stress:num(fields.stress),stool:num(fields.stool),sleep:num(fields.sleep),bowelCount:num(fields.bowelCount),urgency:num(fields.urgency),note:fields.note},'一日の体調を保存しました。'))dailyDrafts.current.set(date,fields)}
 function useMeal(m:Meal,edit=false){if(food.trim()||editing){if(edit)setError('食事の下書きを保存するか、入力をクリアしてから編集してください。');else setIncoming({token:crypto.randomUUID(),food:m.food,amount:m.amount});return}setFood(m.food);setAmount(m.amount);if(edit){setTime(m.time);setKind(m.kind);setEditing(m.id)}else{setTime(japanTime());setEditing(null)}mealId.current='';formRef.current?.scrollIntoView({behavior:'smooth',block:'center'})}
 function useEvent(e:SymptomEvent){if(eventEditing||Object.entries(event).some(([k,v])=>k!=='time'&&v)){setError('時刻別の入力を保存するか、入力をクリアしてから編集してください。');return}setEvent({time:e.time,pain:e.pain?.toString()??'',bloating:e.bloating?.toString()??'',stool:e.stool?.toString()??'',urgency:e.urgency?.toString()??'',note:e.note});setEventEditing(e.id);eventId.current=''}
 const disabled=saving||loading||auth;
 const timeline=[...data.meals.map(m=>({type:'meal' as const,time:m.time,id:m.id,meal:m})),...data.events.map(e=>({type:'event' as const,time:e.time,id:e.id,event:e}))].sort((a,b)=>a.time.localeCompare(b.time));
 return <section className="diary-surface"><div className="section-header"><h2>食事と、おなかの調子を残す</h2><p>食事・症状の時刻と、一日の振り返りを分けて記録できます。</p></div>
 <label htmlFor="record-date">記録する日（日本時間）</label><input id="record-date" className="date-filter" type="date" value={date} disabled={saving||!!editing||!!eventEditing} onChange={e=>{if(e.target.value){dailyDrafts.current.set(date,fields);setDate(e.target.value);setSuccess('')}}}/>
 {auth&&<p className="note">保存には<a href="/signin-with-chatgpt?return_to=/" target="_top">ChatGPTでサインイン</a>してください。</p>}{error&&<p className="error" role="alert">{error}</p>}{success&&<p className="success" role="status">{success}</p>}
 {incoming&&<div className="incoming-meal"><h3>引き継ぐ食事</h3><p>{incoming.food}</p><p className="small">入力中の内容があります。保存せずに置き換えるか、追加するかを選んでください。</p><div className="action-row"><button type="button" className="secondary-button" disabled={saving} onClick={()=>{setFood(incoming.food);setAmount(incoming.amount);setEditing(null);mealId.current='';setIncoming(null)}}>新しい食事として置き換える</button><button type="button" className="secondary-button" disabled={saving} onClick={()=>{setFood((food+'、'+incoming.food).slice(0,2000));setAmount((amount+(amount?'、':'')+incoming.amount).slice(0,300));setIncoming(null)}}>下書きに追加する</button><button type="button" className="text-button" onClick={()=>setIncoming(null)}>今回は使わない</button></div></div>}
 <div className="two-col"><section className="panel"><h3>{editing?'食事を編集':'食事の記録'}</h3><form ref={formRef} onSubmit={e=>{e.preventDefault();void saveMeal()}}><label>食事の種類</label><RadioGroup className="radio-row" aria-label="食事の種類" value={kind} onValueChange={setKind} disabled={disabled}>{['朝食','昼食','夕食','間食'].map(k=><label className="radio-option" key={k}><RadioGroupItem value={k}/>{k}</label>)}</RadioGroup><label htmlFor="meal-time">食べた時刻</label><input id="meal-time" type="time" required value={time} onChange={e=>setTime(e.target.value)} disabled={saving}/><label htmlFor="meal-food">食べたもの・材料</label><textarea id="meal-food" required maxLength={2000} value={food} onChange={e=>setFood(e.target.value)} disabled={saving}/><label htmlFor="meal-amount">食べた量（任意）</label><input id="meal-amount" maxLength={300} value={amount} onChange={e=>setAmount(e.target.value)} disabled={saving} placeholder="実際に食べた量を確認"/><div className="action-row"><button className="primary" disabled={disabled}>{editing?'食事の変更を保存':'食事を保存'}</button><button type="button" className="text-button" disabled={saving} onClick={()=>{setEditing(null);setFood('');setAmount('');mealId.current=''}}>食事の入力をクリア</button></div></form></section>
 <section className="panel"><Tabs defaultValue="event"><TabsList className="record-mode-tabs"><TabsTrigger value="event">時刻別の症状・排便</TabsTrigger><TabsTrigger value="daily">一日の体調</TabsTrigger></TabsList>
 <TabsContent value="event" forceMount className="preserved-tab"><form onSubmit={e=>{e.preventDefault();void saveEvent()}}><h3>{eventEditing?'時刻別の記録を編集':'症状が出たとき・排便したとき'}</h3><label htmlFor="event-time">症状・排便の時刻</label><input id="event-time" type="time" required value={event.time} onChange={e=>setEvent({...event,time:e.target.value})} disabled={saving}/><ScorePicker label="この時刻の腹痛" value={event.pain} onChange={pain=>setEvent({...event,pain})} disabled={disabled}/><ScorePicker label="この時刻の膨満感" value={event.bloating} onChange={bloating=>setEvent({...event,bloating})} disabled={disabled}/><StoolPicker value={event.stool} onChange={stool=>setEvent({...event,stool})} disabled={disabled}/><UrgencyPicker value={event.urgency} onChange={urgency=>setEvent({...event,urgency})} disabled={disabled}/><label htmlFor="event-note">この時刻のメモ（任意）</label><textarea id="event-note" value={event.note} maxLength={2000} onChange={e=>setEvent({...event,note:e.target.value})} disabled={saving}/><div className="action-row"><button className="primary" disabled={disabled}>時刻別の体調を保存</button><button type="button" className="text-button" disabled={saving} onClick={()=>{setEvent(blankEvent());setEventEditing(null);eventId.current=''}}>時刻別の入力をクリア</button></div></form></TabsContent>
 <TabsContent value="daily" forceMount className="preserved-tab"><form onSubmit={e=>{e.preventDefault();void saveDaily()}}><h3>一日の振り返り</h3><ScorePicker label="一日の腹痛" value={fields.pain} onChange={pain=>setDaily({pain})} disabled={disabled}/><ScorePicker label="一日の膨満感" value={fields.bloating} onChange={bloating=>setDaily({bloating})} disabled={disabled}/><ScorePicker label="一日のストレス" value={fields.stress} onChange={stress=>setDaily({stress})} disabled={disabled}/><StoolPicker value={fields.stool} onChange={stool=>setDaily({stool})} disabled={disabled}/><UrgencyPicker value={fields.urgency} onChange={urgency=>setDaily({urgency})} disabled={disabled}/><div className="inline-fields"><div><label htmlFor="bowel-count">この日の排便回数</label><input id="bowel-count" type="number" min="0" max="50" step="1" value={fields.bowelCount} onChange={e=>setDaily({bowelCount:e.target.value})} disabled={saving}/><p className="small">空欄は未記録。時刻別の便形状の記録は{data.events.filter(e=>e.stool!==null).length}件です。</p></div><div><label htmlFor="symptom-sleep">睡眠時間（時間）</label><input id="symptom-sleep" type="number" min="0" max="24" step="0.5" value={fields.sleep} onChange={e=>setDaily({sleep:e.target.value})} disabled={saving}/></div></div><label htmlFor="symptom-note">一日の気づき・服薬など（任意）</label><textarea id="symptom-note" maxLength={2000} value={fields.note} onChange={e=>setDaily({note:e.target.value})} disabled={saving}/><div className="action-row"><button className="primary" disabled={disabled}>一日の体調を保存</button></div><p className="small">保存すると、この日の振り返りを更新します。</p></form></TabsContent></Tabs></section></div>
 <section className="panel timeline-panel"><h3>{date} の食事・症状</h3>{loading?<p role="status">記録を読み込んでいます…</p>:<>{!timeline.length&&!data.symptoms&&<p className="empty-result">まだこの日の記録がありません。</p>}{timeline.map(item=><article className={'entry timeline-entry '+item.type} key={item.id}><span className="timeline-time">{item.time}</span><div>{item.type==='meal'?<><small>{item.meal.kind} · 食事</small><h3>{item.meal.food}</h3>{item.meal.amount&&<p>量：{item.meal.amount}</p>}<div className="action-row"><button type="button" className="text-button" disabled={disabled} onClick={()=>useMeal(item.meal)}>この食事をコピー</button><button type="button" className="text-button" disabled={disabled} onClick={()=>useMeal(item.meal,true)}>食事を編集</button><button type="button" className="text-button danger-text" disabled={disabled} onClick={()=>void mutate('DELETE',{type:'meal',id:item.id},'食事を削除しました。「削除した記録」から戻せます。')}>食事を削除</button></div></>:<><small>症状・排便</small><p>腹痛 {item.event.pain??'未記録'} ／ 膨満感 {item.event.bloating??'未記録'}</p><p>便の形 {item.event.stool===null?'未記録':item.event.stool+' · '+stoolLabels[item.event.stool-1]} ／ 切迫感 {item.event.urgency??'未記録'}</p>{item.event.note&&<p>{item.event.note}</p>}<div className="action-row"><button type="button" className="text-button" disabled={disabled} onClick={()=>useEvent(item.event)}>時刻別の記録を編集</button><button type="button" className="text-button danger-text" disabled={disabled} onClick={()=>void mutate('DELETE',{type:'event',id:item.id},'記録を削除しました。「削除した記録」から戻せます。')}>時刻別の記録を削除</button></div></>}</div></article>)}{data.symptoms&&<article className="entry"><small>時刻を指定しない、一日の振り返り</small><p>腹痛 {data.symptoms.pain??'未記録'} ／ 膨満感 {data.symptoms.bloating??'未記録'} ／ ストレス {data.symptoms.stress??'未記録'}</p><p>排便 {data.symptoms.bowel_count??'未記録'} 回 ／ 睡眠 {data.symptoms.sleep??'未記録'} 時間</p>{data.symptoms.note&&<p>{data.symptoms.note}</p>}</article>}</>}</section>
 {(data.deletedMeals.length>0||data.deletedEvents.length>0)&&<section className="panel deleted-records"><h3>削除した記録（元に戻せます）</h3>{[...data.deletedMeals.map(m=>({id:m.id,type:'meal',label:m.time+' · '+m.food})),...data.deletedEvents.map(e=>({id:e.id,type:'event',label:e.time+' · 症状・排便'}))].map(r=><article className="entry" key={r.id}><p>{r.label}</p><button type="button" className="text-button" disabled={disabled} onClick={()=>void mutate('PATCH',{type:r.type,id:r.id,action:'restore'},'記録を元に戻しました。')}>この記録を元に戻す</button></article>)}</section>}
 <p className="note">食事と症状の並びは原因の特定ではありません。睡眠・ストレス・服薬も一緒に振り返りましょう。</p></section>
}

