'use client';
import {useEffect,useState,useId} from 'react';
import {Plus,X,ChevronDown,Star} from 'lucide-react';
import {usePreferences} from './preferences-ui';
import {findFood} from '@/lib/foods';
import {portionsFor} from '@/lib/portions';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {commonFoods,foodCategories,foodKey,canonicalFoodName,type FoodCategory,type PickerFood} from '@/lib/food-picker';
type Props={selected:string[];onSelectedChange:(foods:string[])=>void;manual:string;onManualChange:(text:string)=>void;mode?:'check'|'wanted'|'preferred'|'excluded'};
export default function FoodPicker({selected,onSelectedChange,manual,onManualChange,mode='check'}:Props){
 const id=useId();const manualId=id+'-manual';const nameId=id+'-name';const categoryId=id+'-category';
 const heading=mode==='wanted'?'必ず使う食材':mode==='preferred'?'できれば使いたい食材':mode==='excluded'?'避けたい食材':'選んだ食材';const prefs=usePreferences();
 const [category,setCategory]=useState<string>('vegetables');const [custom,setCustom]=useState<PickerFood[]>([]);
 const savedCustom=custom.filter(f=>!commonFoods.some(base=>foodKey(base.name)===foodKey(f.name)));
 const [manualOpen,setManualOpen]=useState(false);const [registerOpen,setRegisterOpen]=useState(false);
 const [name,setName]=useState('');const [newCategory,setNewCategory]=useState<FoodCategory>('vegetables');
 const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [auth,setAuth]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{function receive(event:Event){const food=(event as CustomEvent<PickerFood>).detail;setCustom(previous=>previous.some(f=>f.id===food.id)?previous:[...previous,food])}window.addEventListener('food-choice-added',receive);return()=>window.removeEventListener('food-choice-added',receive)},[]);
 useEffect(()=>{if(manual)setManualOpen(true)},[manual]);
 useEffect(()=>{const abort=new AbortController();fetch('/api/foods',{cache:'no-store',signal:abort.signal}).then(async r=>{const v=await r.json() as {foods:PickerFood[];error:string};if(!r.ok){if(r.status===401){setAuth(true);return}throw new Error(v.error)}setCustom(v.foods)}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'読み込みに失敗しました。')}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[]);
 function toggle(food:string){if(!selected.includes(food))prefs.remember([food]);onSelectedChange(selected.includes(food)?selected.filter(s=>s!==food):[...selected,food])}
 function option(f:PickerFood){const known=findFood(f.name);return <div className={'food-option '+(selected.includes(f.name)?'is-selected':'')} key={f.id}><label><Checkbox checked={selected.includes(f.name)} onCheckedChange={()=>toggle(f.name)} disabled={saving}/><span>{f.name}{savedCustom.some(s=>s.id===f.id)&&<small>自分で追加</small>}{!known&&<small className="missing-data">分類未収録</small>}{known&&!portionsFor(f.name).length&&<small>量別情報は未収録</small>}</span></label><button type="button" className="favorite-button" aria-label={f.name+(prefs.favorites.includes(f.name)?'のお気に入りを解除':'をお気に入りに登録')} aria-pressed={prefs.favorites.includes(f.name)} disabled={prefs.loading||prefs.saving} onClick={()=>prefs.toggleFavorite(f.name)}><Star size={17} fill={prefs.favorites.includes(f.name)?'currentColor':'none'}/></button></div>}
 async function add(){
  setNotice('');setError('');const clean=canonicalFoodName(name);if(!clean||/[、,，\n\r]/.test(clean)){setError('食材名を一つだけ入力してください。');return}
  const existing=[...commonFoods,...custom].find(f=>foodKey(f.name)===foodKey(clean));if(existing){setCategory(existing.category);setError('この食材はすでに選択肢にあります。');return}
  setSaving(true);try{const r=await fetch('/api/foods',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:clean,category:newCategory})});const v=await r.json() as {food:PickerFood;error:string};if(!r.ok){if(r.status===401)setAuth(true);throw new Error(v.error)}window.dispatchEvent(new CustomEvent('food-choice-added',{detail:v.food}));setCategory(v.food.category);onSelectedChange([...selected,v.food.name]);prefs.remember([v.food.name]);setName('');setNotice('「'+v.food.name+'」を選択肢に保存して選択しました。');}
  catch(e){setError(e instanceof Error?e.message:'保存できませんでした。')}finally{setSaving(false)}
 }
 return <div className="food-picker"><p className="picker-instruction">{mode==='check'?'グループから食材を選んでください。複数選べます。':heading+'を選んでください。複数選べます。'}</p>{[['お気に入り',prefs.favorites],['最近使った食材',prefs.recent.filter(n=>!prefs.favorites.includes(n))]] .map(([title,names])=>(names as string[]).length>0&&<section className="quick-foods" aria-label={title as string} key={title as string}><h4>{title as string}</h4><div className="quick-food-buttons">{(names as string[]).map(n=><button type="button" className={selected.includes(n)?'is-selected':''} aria-pressed={selected.includes(n)} key={n} onClick={()=>toggle(n)}>{n}</button>)}</div></section>)}<Tabs value={category} onValueChange={setCategory}><TabsList className="category-tabs" aria-label="食材のグループ">{foodCategories.map(c=><TabsTrigger key={c.id} value={c.id}>{c.label}</TabsTrigger>)}</TabsList>{foodCategories.map(c=>{const list=[...commonFoods.filter(f=>f.category===c.id),...savedCustom.filter(f=>f.category===c.id)];return <TabsContent key={c.id} value={c.id}><div className="food-options">{list.map(option)}</div>{!list.length&&<p className="picker-empty">このグループにはまだ選択肢がありません。手入力するか、自分の食材を追加できます。</p>}</TabsContent>})}</Tabs>
 <div className="picked-summary"><div className="picked-heading"><strong>{heading} <span>{selected.length}個</span></strong>{selected.length>0&&<button className="text-button" type="button" onClick={()=>onSelectedChange([])} disabled={saving}>選択をクリア</button>}</div>{selected.length>0?<div className="picked-chips">{selected.map(s=><button type="button" key={s} aria-label={s+'の選択を解除'} onClick={()=>toggle(s)} disabled={saving}>{s}<X size={14}/></button>)}</div>:<p className="small">まだ食材を選んでいません。</p>}</div>
 <Collapsible open={manualOpen} onOpenChange={setManualOpen} className="picker-fold"><CollapsibleTrigger className="fold-trigger" type="button"><span>一覧にない食材・あまり使わない食材を入力</span><ChevronDown size={17}/></CollapsibleTrigger><CollapsibleContent><label htmlFor={manualId}>{mode==='check'?'今回だけ入力する材料・量（任意）':heading+'を手入力（任意）'}</label><textarea id={manualId} value={manual} onChange={e=>onManualChange(e.target.value)} maxLength={2000} placeholder={mode==='check'?'例：食材名 10g、別の食材名':'例：食材名、別の食材名'}/><p className="small">{mode==='check'?'選んだ食材と合わせて確認します。':'選んだ食材と合わせて献立の条件にします。'}ここに入力した食材は選択肢には保存しません。</p></CollapsibleContent></Collapsible>
 <Collapsible open={registerOpen} onOpenChange={setRegisterOpen} className="picker-fold"><CollapsibleTrigger className="fold-trigger" type="button"><span><Plus size={17}/>自分の食材を選択肢に追加する</span><ChevronDown size={17}/></CollapsibleTrigger><CollapsibleContent>{auth?<p className="note">次回も選べるように保存するには、<a href="/signin-with-chatgpt?return_to=/" target="_top">ChatGPTでサインイン</a>してください。</p>:<><div className="custom-food-fields"><div><label htmlFor={nameId}>追加する食材名</label><input id={nameId} value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder="例：ズッキーニ" disabled={saving}/></div><div><label htmlFor={categoryId}>追加先のグループ</label><Select value={newCategory} onValueChange={v=>setNewCategory(v as FoodCategory)} disabled={saving}><SelectTrigger id={categoryId} className="category-select"><SelectValue/></SelectTrigger><SelectContent>{foodCategories.map(c=><SelectItem key={c.id} value={c.id}>{c.label}</SelectItem>)}</SelectContent></Select></div></div><button type="button" className="secondary-button" onClick={()=>void add()} disabled={saving||loading||!name.trim()}>{saving?'保存中…':'選択肢に保存して選ぶ'}</button></>}<p className="small">追加した食材名からFODMAPの情報を確認します。根拠がない食材は判定保留のままです。</p></CollapsibleContent></Collapsible>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 </div>
}

