'use client';
import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {calendarRange,dateOffset,japanToday,type RangeData} from '@/lib/diary';
const empty:RangeData={meals:[],events:[],days:[]};
export default function Reports({revision,active}:{revision:number;active:boolean}){
 const [period,setPeriod]=useState<'week'|'month'>('week');const [date,setDate]=useState(japanToday);const [data,setData]=useState<RangeData>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [auth,setAuth]=useState(false);const range=calendarRange(date,period);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setData(empty);setError('');fetch('/api/diary?from='+range.from+'&to='+range.to,{cache:'no-store',signal:abort.signal}).then(async r=>{const v=await r.json() as RangeData & {error?:string};if(!r.ok){setAuth(r.status===401);throw new Error(v.error)}if(!abort.signal.aborted){setAuth(false);setData(v)}}).catch(e=>{if(!abort.signal.aborted)setError(e.message??'記録を読み込めません。')}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[range.from,range.to,revision]);
 const chart=[];for(let day=range.from;day<=range.to;day=dateOffset(day,1)){const daily=data.days.find(d=>d.date===day);const events=data.events.filter(e=>e.date===day);const max=(key:'pain'|'bloating')=>{const values=[daily?.[key],...events.map(e=>e[key])].filter((n):n is number=>n!=null);return values.length?Math.max(...values):null};chart.push({date:day,label:day.slice(5),pain:max('pain'),bloating:max('bloating'),stress:daily?.stress??null,bowelCount:daily?.bowel_count??(events.some(e=>e.stool!==null)?events.filter(e=>e.stool!==null).length:null)})}
 const timeline=[...data.meals.map(m=>({id:m.id,date:m.date,time:m.time,kind:m.kind,detail:m.food+(m.amount?' ／ '+m.amount:''),type:'meal'})),...data.events.map(e=>({id:e.id,date:e.date,time:e.time,kind:'症状・排便',detail:'腹痛 '+(e.pain??'未記録')+' ／ 膨満感 '+(e.bloating??'未記録')+' ／ 便形状 '+(e.stool??'未記録')+' ／ 切迫感 '+(e.urgency??'未記録')+(e.note?' ／ '+e.note:''),type:'event'})),...data.days.map(d=>({id:'daily-'+d.date,date:d.date,time:'',kind:'一日の体調',detail:'腹痛 '+(d.pain??'未記録')+' ／ 膨満感 '+(d.bloating??'未記録')+' ／ ストレス '+(d.stress??'未記録')+' ／ 睡眠 '+(d.sleep??'未記録')+'時間 ／ 排便回数 '+(d.bowel_count??'未記録')+(d.note?' ／ '+d.note:''),type:'daily'}))].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 const hasRecords=timeline.length>0;
 function download(){const link=document.createElement('a');link.href='/api/export?from='+range.from+'&to='+range.to;link.download='おなかノート_'+range.from+'_'+range.to+'.csv';document.body.appendChild(link);link.click();link.remove()}
 return <section className="reports-surface"><div className="section-header"><h2>食事と体調を振り返る</h2><p>食事・症状を同じ時間軸で確認し、診察に持参する記録を作れます。</p></div><div className="report-controls no-print"><fieldset><legend>表示する期間</legend><RadioGroup aria-label="表示する期間" className="radio-row" value={period} onValueChange={v=>setPeriod(v as 'week'|'month')}>{[['week','7日間'],['month','1か月']].map(([value,label])=><label className="radio-option" key={value}><RadioGroupItem value={value}/>{label}</label>)}</RadioGroup></fieldset><div><label htmlFor="report-date">基準日（1か月表示はこの日が属する月）</label><input id="report-date" type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></div></div>
 <p className="report-range">{range.from} 〜 {range.to}（日本時間）</p>{auth&&<p className="note no-print"><a href="/signin-with-chatgpt?return_to=/" target="_top">ChatGPTでサインイン</a>して記録を表示してください。</p>}{error&&<p className="error" role="alert">{error}</p>}
 <div className="action-row no-print"><button type="button" className="secondary-button" disabled={loading||!!error||!hasRecords} onClick={download}>記録をCSVで保存</button><button type="button" className="secondary-button" disabled={loading||!!error||!hasRecords} onClick={()=>window.print()}>診察用に印刷・PDF保存</button><span className="small">PDFは印刷画面で「PDFに保存」を選べます。</span></div>
 {loading?<p role="status">記録を読み込んでいます…</p>:!hasRecords&&!error?<div className="empty-result"><h3>この期間の記録はありません。</h3><p>食事・体調を記録すると、ここに表示されます。</p></div>:hasRecords&&<><div className="report-stats"><span>食事 <strong>{data.meals.length}件</strong></span><span>時刻別の体調 <strong>{data.events.length}件</strong></span><span>一日の体調 <strong>{data.days.length}日分</strong></span></div><div className="two-col report-charts"><section className="panel"><h3>症状・ストレスの変化</h3><p className="small">腹痛・膨満感は、その日に記録した最大値（0〜10）。空欄は未記録です。</p><div className="chart-frame">{active&&<ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:300,height:270}}><LineChart data={chart} margin={{left:-15,right:10,top:15,bottom:8}} accessibilityLayer><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" minTickGap={24}/><YAxis domain={[0,10]} ticks={[0,2,4,6,8,10]}/><Tooltip/><Legend/><Line name="腹痛" dataKey="pain" stroke="#b43c56" strokeWidth={2} dot={{r:4}} connectNulls={false} isAnimationActive={false}/><Line name="膨満感" dataKey="bloating" stroke="#11776e" strokeWidth={2} dot={{r:4}} connectNulls={false} isAnimationActive={false}/><Line name="ストレス" dataKey="stress" stroke="#3c65a6" strokeWidth={2} dot={{r:3}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>}</div></section><section className="panel"><h3>排便回数の記録</h3><p className="small">一日の入力を優先。空欄の日は便形状を記録した件数を表示します。全排便を記録したとは限りません。</p><div className="chart-frame">{active&&<ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:300,height:270}}><BarChart data={chart} margin={{left:-15,right:10,top:15,bottom:8}} accessibilityLayer><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" minTickGap={24}/><YAxis allowDecimals={false}/><Tooltip/><Bar name="排便回数・記録件数" dataKey="bowelCount" fill="#17776e" isAnimationActive={false}/></BarChart></ResponsiveContainer>}</div></section></div>
 <section className="panel report-table"><h3>食事・症状の時系列</h3><p className="small">日付・時刻の順に表示。一日の体調は時刻のない別の記録です。</p><div className="table-scroll"><table><caption className="sr-only">{range.from}から{range.to}までの食事・体調の記録</caption><thead><tr><th>日付</th><th>時刻</th><th>種類</th><th>記録内容</th></tr></thead><tbody>{timeline.map(item=><tr key={item.id}><td>{item.date}</td><td>{item.time||'時刻なし'}</td><td>{item.kind}</td><td>{item.detail}</td></tr>)}</tbody></table></div></section></>}
 <p className="note">記録の並びやグラフは食事と症状の因果関係を判断するものではありません。医師・管理栄養士と振り返るための記録です。</p>
 </section>
}


