export const source='https://www.monashfodmap.com/about-fodmap-and-ibs/high-and-low-fodmap-foods/';
export const shoppingSource='https://www.monashfodmap.com/blog/low-fodmap-shopping-list/';
export type Food={name:string;aliases:string[];status:'low'|'high'|'caution';group:string;note:string;sourceUrl:string};
const row=(name:string,aliases:string[],status:Food['status'],group:string,note:string,sourceUrl=source):Food=>({name,aliases:[name,...aliases],status,group,note,sourceUrl});
const servingNote='公開資料の食品例です。一食量は公式アプリで確認。';
const plainMeatNote='味付けのない食材が対象。加工品・たれ・漬け込みは別途確認。';
export const foods:Food[]=[
row('鶏肉',['鶏むね肉','鶏もも肉','チキン'],'low','たんぱく質','味付けのない肉が対象。加工品や漬け込みは別途確認。'),
row('魚',[],'low','たんぱく質','味付けのない魚が対象。ソース・たれは別途確認。'),
row('鮭',['さけ','サケ','サーモン'],'low','魚',plainMeatNote,shoppingSource),
row('鱈',['たら','タラ'],'low','魚',plainMeatNote,shoppingSource),
row('卵',['たまご','玉子'],'low','たんぱく質','卵そのものが対象。'),
row('木綿豆腐',['もめん豆腐'],'low','たんぱく質','絹ごし豆腐とは区別。量は公式情報で確認。'),
row('にんじん',['人参','ニンジン'],'low','野菜','一食量の詳細は公式アプリで確認。'),
row('じゃがいも',['ジャガイモ','馬鈴薯'],'low','野菜','ソースなどの追加材料にも注意。'),
row('きゅうり',['胡瓜','キュウリ'],'low','野菜','一食量の詳細は公式アプリで確認。'),
row('なす',['茄子','ナス'],'low','野菜','一食量の詳細は公式アプリで確認。'),
row('レタス',[],'low','野菜','一食量の詳細は公式アプリで確認。'),
row('キウイ',['キウイフルーツ'],'low','果物','一食量の詳細は公式アプリで確認。'),
row('乳糖除去牛乳',['ラクトースフリー牛乳'],'low','乳製品','通常の牛乳とは区別。'),
row('玉ねぎ',['たまねぎ','タマネギ','玉葱','オニオン'],'high','フルクタン','一般的な食品分類。粉末やソース中の材料にも注意。'),
row('にんにく',['ニンニク','大蒜','ガーリック'],'high','フルクタン','一般的な食品分類。少量の基準は別途確認。'),
row('りんご',['リンゴ','林檎'],'high','果糖・ソルビトール','一般的な食品分類。'),
row('牛乳',['普通牛乳','ミルク'],'high','乳糖','乳糖を含む通常の牛乳が対象。'),
row('はちみつ',['蜂蜜','ハチミツ'],'high','果糖','一般的な食品分類。'),
row('カシューナッツ',['カシュー'],'high','フルクタン・GOS','一般的な食品分類。'),
row('小麦パスタ',['パスタ','スパゲティ'],'high','フルクタン','小麦由来が対象。米・コーン由来は区別。'),
row('豆乳',[],'caution','原料による違い','丸大豆由来と大豆たんぱく由来で評価が異なります。原材料を確認。'),
row('きのこ',['キノコ','茸'],'caution','種類による違い','種類と量を特定する必要があります。'),
row('ひらたけ',['ヒラタケ'],'low','野菜',servingNote,shoppingSource),
row('トマト',[],'caution','品種・量による違い','公開資料の献立例にありますが、量別の値はこの試作に未収録。品種と一食量を公式情報で確認。','https://www.monashfodmap.com/blog/low-fodmap-meal-planning/'),
row('ほうれん草',['ほうれんそう','ホウレンソウ'],'low','野菜',servingNote,shoppingSource),
row('チンゲン菜',['青梗菜','チンゲンサイ'],'low','野菜',servingNote),
row('ピーマン',['緑ピーマン'],'low','野菜','緑色のものが対象。赤いパプリカとは区別。一食量は公式アプリで確認。'),
row('いんげん',['インゲン','さやいんげん'],'low','野菜',servingNote),
row('さつまいも',['サツマイモ','さつま芋'],'low','野菜',servingNote,shoppingSource),
row('キャベツ',[],'caution','品種・量による違い','公開資料には白・赤キャベツの例があります。品種と一食量を確認。',shoppingSource),
row('かぼちゃ',['カボチャ','南瓜'],'caution','品種による違い','公開資料はkabocha pumpkinの例です。品種・一食量を確認。',shoppingSource),
row('ブロッコリー',[],'caution','部位による違い','公開資料の低FODMAP例は房の部分。茎を含む場合は別途確認。',shoppingSource),
row('とうもろこし',['トウモロコシ','コーン'],'low','野菜','粒の部分が対象。一食量は公式アプリで確認。',shoppingSource),
row('トマト缶',['缶詰トマト'],'low','野菜','缶詰のトマトが対象。玉ねぎ・にんにく入りのソースとは区別。',shoppingSource),
row('アスパラガス',['アスパラ'],'high','野菜',servingNote),
row('グリーンピース',[],'high','野菜',servingNote),
row('みかん',['ミカン','蜜柑','マンダリン'],'low','果物',servingNote),
row('オレンジ',[],'low','果物',servingNote),
row('パイナップル',['パイン'],'low','果物',servingNote),
row('ブルーベリー',[],'low','果物',servingNote),
row('いちご',['イチゴ','苺'],'low','果物',servingNote,shoppingSource),
row('バナナ',[],'caution','熟度による違い','公開資料は硬めのバナナの例です。熟し具合・一食量を確認。',shoppingSource),
row('もも',['モモ','桃'],'high','果物',servingNote),
row('梨',['なし','ナシ','洋梨','洋なし'],'high','果物',servingNote),
row('すいか',['スイカ','西瓜'],'high','果物',servingNote),
row('マンゴー',[],'high','果物',servingNote),
row('さくらんぼ',['サクランボ','チェリー'],'high','果物',servingNote),
row('豚肉',['ポーク'],'low','たんぱく質',plainMeatNote,shoppingSource),
row('牛肉',['ビーフ'],'low','たんぱく質',plainMeatNote,shoppingSource),
row('えび',['エビ','海老'],'low','魚介',plainMeatNote,shoppingSource),
row('いか',['イカ','烏賊'],'low','魚介',plainMeatNote,shoppingSource),
row('あさり',['アサリ'],'low','魚介',plainMeatNote,shoppingSource),
row('アーモンドミルク',[],'low','乳代替品','原材料・添加物と一食量を確認。'),
row('大豆たんぱく由来の豆乳',['大豆たんぱく豆乳'],'low','乳代替品','丸大豆由来の豆乳とは区別。原材料を確認。'),
row('ハードチーズ',['硬質チーズ'],'low','乳製品','硬質チーズが対象。一般的なチーズ全体の判定ではありません。'),
row('ヨーグルト',[],'high','乳糖','通常の乳糖を含む製品が対象。乳糖除去品は区別。'),
row('アイスクリーム',[],'high','乳糖','通常の乳製品が対象。乳糖除去品・植物由来品は区別。'),
row('バター',[],'low','乳製品','バターそのものが対象。混合スプレッドや追加材料は確認。'),
row('ごはん',['ご飯','米','白米','ライス'],'low','主食','米と水で炊いたごはんが対象。味付きのごはんは材料を別途確認。',shoppingSource),
row('オートミール',['ロールドオーツ','オーツ麦'],'low','主食',servingNote),
row('米粉パスタ',[],'low','主食','米由来が対象。小麦・豆類などを含む混合品は原材料を確認。'),
row('米麺',['ライスヌードル','ビーフン'],'low','主食','米由来が対象。混合原料や添付のスープは別途確認。',shoppingSource),
row('食パン',['小麦パン'],'high','フルクタン','一般的な小麦由来のパンが対象。製法・原材料で違いがあります。'),
row('砂糖',['上白糖','グラニュー糖'],'low','調味料','通常の砂糖が対象。甘味料を混合した製品とは区別。'),
row('メープルシロップ',[],'low','調味料','メープルシロップそのものが対象。混合シロップは原材料を確認。'),
row('しょうゆ',['醤油','しょう油'],'low','調味料','公開資料の食品例。調味だれ・だし入り製品は追加材料を確認。'),
row('マヨネーズ',[],'low','調味料','公開資料の食品例。玉ねぎ・にんにくなどの追加材料を確認。'),
row('酢',['お酢'],'low','調味料','酢が対象。合わせ酢やドレッシングは追加材料を確認。',shoppingSource),
row('オリーブオイル',['オリーブ油'],'low','油脂','油そのものが対象。具入り・調味オイルは材料を確認。',shoppingSource),
row('サラダ油',[],'low','油脂','油そのものが対象。混合調味料は材料を確認。',shoppingSource),
row('くるみ',['クルミ','胡桃'],'low','ナッツ',servingNote),
row('ピーナッツ',['落花生','ピーナツ'],'low','ナッツ',servingNote),
row('マカダミアナッツ',['マカダミア'],'low','ナッツ',servingNote),
row('ごま',['ゴマ','胡麻'],'low','種子',servingNote,shoppingSource),
row('ピスタチオ',[],'high','ナッツ',servingNote),
row('ダークチョコレート',[],'low','菓子','乳入り・糖アルコール入りなどは区別。一食量を確認。'),
];
export const normalize=(s:string)=>s.normalize('NFKC').trim().toLowerCase().replace(/\s/g,'');
export function findFood(raw:string){const key=normalize(raw);return foods.find(f=>f.aliases.some(a=>normalize(a)===key))}
export type Result={input:string;food?:Food;amount?:string;status:'low'|'high'|'caution'|'unknown'};
export function checkFoods(text:string):Result[]{return text.split(/[,、\n]/).map(s=>s.trim()).filter(Boolean).map(input=>{
const match=input.match(/\s*(\d+(?:\.\d+)?)\s*(g|グラム|ml|mL|個|枚|杯)\s*$/i);
const name=match?input.slice(0,match.index).trim():input;const food=findFood(name);
return {input,food,amount:match?.[0].trim(),status:food?.status??'unknown'};});}
export const labels={low:'低FODMAPの候補',caution:'注意・条件を確認',high:'高FODMAPで控える目安',unknown:'判定保留'};
